spring:
  application:
    name: monitor-demo
server:
  port: 8080

# influxdb
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    health:
      show-details: ALWAYS
      enabled: true
    beans:
      enabled: true
  influx:
    metrics:
      export:
        enabled: true
        db: mydb2
        uri: http://192.168.127.10:8086
        user-name: faris
        password: password
        connect-timeout: 1s
        read-timeout: 10s
        auto-create-db: true
        step: 1m
        consistency: one
        compressed: true
        batch-size: 1000
